framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # Use Redis as the default cache adapter
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Namespaced pools use the above "app" backend by default
        pools:
            # Artist data cache - for artist info, search results, etc.
            cache.artist:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 2592000  # 30 days
                tags: true

            # Album data cache - for album info, search results, releases
            cache.album:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 2592000  # 30 days
                tags: true

            # Track data cache - for track listings, recordings
            cache.track:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 2592000  # 30 days
                tags: true

            # Cover art cache - for album covers from Cover Art Archive
            cache.cover:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 7776000  # 90 days
                tags: true

            # Image cache - for artist images from Last.fm, Spotify, etc.
            cache.image:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 7776000  # 90 days
                tags: true

            # General HTTP cache - for other requests
            cache.http:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 2592000  # 30 days
                tags: true

when@test:
    framework:
        cache:
            # Use filesystem cache for tests instead of Redis
            app: cache.adapter.filesystem
            default_redis_provider: ~

            # Namespaced pools use filesystem adapters for tests
            pools:
                # Artist data cache - for artist info, search results, etc.
                cache.artist:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true

                # Album data cache - for album info, search results, releases
                cache.album:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true

                # Track data cache - for track listings, recordings
                cache.track:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true

                # Cover art cache - for album covers from Cover Art Archive
                cache.cover:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true

                # Image cache - for artist images from Last.fm, Spotify, etc.
                cache.image:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true

                # General HTTP cache - for other requests
                cache.http:
                    adapter: cache.adapter.filesystem
                    default_lifetime: 2592000  # 30 days
                    tags: true
