# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #default parameter for services
    locale: 'en'
    app.locale: 'en'
    app.timezone: 'UTC'
    app.name: 'Musicarr'
    default_user_agent: 'Musicarr/1.0.0'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Plugin services
    App\Service\RemotePluginDiscoveryService:
        arguments:
            $httpClient: '@http_client'
            $cache: '@cache.app'

    App\Service\RemotePluginInstallerService:
        arguments:
            $filesystem: '@filesystem'

    # tag every service that implements the plugin interface
    _instanceof:
        App\Plugin\PluginInterface:
            tags: ['app.plugin']

    # Aliases for cache services used by PluginManager
    Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface: '@cache_clearer'

    # Plugin system services
    App\Plugin\PluginManager: ~

    App\Plugin\Routing\PluginRouteLoader:
        arguments:
            $pluginManager: '@App\Plugin\PluginManager'
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'routing.loader' }

    # Configuration domain services

    App\Configuration\Domain\AssociationConfigurationDomain:
        tags:
            - { name: 'app.configuration.domain' }

    App\Configuration\Domain\MetadataConfigurationDomain:
        tags:
            - { name: 'app.configuration.domain' }

    App\Configuration\Domain\AlbumImportConfigurationDomain:
        tags:
            - { name: 'app.configuration.domain' }

    App\Configuration\Domain\AudioQualityConfigurationDomain:
        tags:
            - { name: 'app.configuration.domain' }


